# Site settings
name: Lidya Ghebreigzabher Okubamichael
email: lidya94gher@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Fullstack developer,HTML5, CSS3, Ruby,Ruby on rails, javascript, react, Java, C, PHP, Pair Programming"
skills: "Junior software developer at microverse, Mentor at microverse"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/lidya-ghebreigziabher/
  - title: github
    url: https://github.com/Lidya1234
  - title: twitter
    url: https://twitter.com/Lidya42676629
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
